# Generated by Django 5.2.16 on 2026-07-15 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'specialties',
                'db_table': 'specialties',
                'indexes': [models.Index(fields=['clinic', 'is_active'], name='specialties_clinic__17c602_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'slug'), name='uq_specialty_clinic_slug')],
            },
        ),
    ]
