# Generated by Django 5.2.16 on 2026-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_id_alter_clinicbusinesshours_id'),
        ('specialties', '0002_alter_specialty_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='specialty',
            name='specialties_clinic__17c602_idx',
        ),
        migrations.AlterField(
            model_name='specialty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['clinic', 'is_active'], name='idx_spec_active_live'),
        ),
    ]
