# Generated by Django 5.2.16 on 2026-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0003_remove_specialty_specialties_clinic__17c602_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='category',
            field=models.CharField(blank=True, choices=[('Primary Care', 'Primary Care'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Gastroenterology', 'Gastroenterology'), ('Neurology', 'Neurology'), ('Psychiatry / Mental Health', 'Psychiatry / Mental Health'), ('OB-GYN', 'OB-GYN'), ('Orthopedics', 'Orthopedics'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Dentistry', 'Dentistry'), ('Pediatrics', 'Pediatrics'), ('Endocrinology', 'Endocrinology'), ('Pulmonology', 'Pulmonology'), ('Urology', 'Urology'), ('Nephrology', 'Nephrology'), ('Oncology', 'Oncology'), ('Sleep Medicine', 'Sleep Medicine'), ('Pain Management', 'Pain Management'), ('Rheumatology', 'Rheumatology'), ('Allergy & Immunology', 'Allergy & Immunology'), ('Podiatry', 'Podiatry'), ('Surgery', 'Surgery'), ('Aesthetics / Cosmetic', 'Aesthetics / Cosmetic'), ('Physical Therapy', 'Physical Therapy'), ('Laboratory / Diagnostics', 'Laboratory / Diagnostics'), ('Other', 'Other')], default='', max_length=32),
        ),
    ]
