# Generated by Django 5.2.16 on 2026-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_at_alter_clinicstaff_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('email_verify', 'Email verify'), ('password_reset', 'Password reset'), ('password_change', 'Password change'), ('enter_clinic', 'Enter clinic'), ('exit_clinic', 'Exit clinic'), ('clinic_create', 'Clinic create'), ('clinic_status', 'Clinic status change'), ('document_upload', 'Document upload'), ('document_delete', 'Document delete'), ('doctor_delete', 'Doctor delete'), ('appointment_cancel', 'Appointment cancel'), ('insurance_update', 'Insurance update'), ('tenant_select', 'Tenant select'), ('subscription_checkout_started', 'Subscription checkout started'), ('subscription_cancel_requested', 'Subscription cancel requested'), ('subscription_change_requested', 'Subscription change requested')], max_length=64),
        ),
    ]
