# Generated by Django 5.2.16 on 2026-08-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_action_alter_staffauthtoken_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('email_verify', 'Email verify'), ('password_reset', 'Password reset'), ('password_change', 'Password change'), ('phone_verify_requested', 'Phone verification requested'), ('phone_verify_approved', 'Phone verification approved'), ('phone_verify_failed', 'Phone verification failed'), ('enter_clinic', 'Enter clinic'), ('exit_clinic', 'Exit clinic'), ('clinic_create', 'Clinic create'), ('clinic_status', 'Clinic status change'), ('document_upload', 'Document upload'), ('document_delete', 'Document delete'), ('doctor_delete', 'Doctor delete'), ('appointment_cancel', 'Appointment cancel'), ('insurance_update', 'Insurance update'), ('tenant_select', 'Tenant select'), ('subscription_checkout_started', 'Subscription checkout started'), ('subscription_cancel_requested', 'Subscription cancel requested'), ('subscription_change_requested', 'Subscription change requested'), ('application_approved', 'Clinic application approved'), ('application_rejected', 'Clinic application rejected'), ('invite_accepted', 'Invitation accepted'), ('user_invite', 'User invited'), ('user_update', 'User updated'), ('plan_update', 'Billing plan updated')], max_length=64),
        ),
    ]
