--
-- PostgreSQL database dump
--

\restrict mkP3GKu6PYIHA70xWhJFrVx9Iu1xFxqvfWI4bMrA0etHEzmuJ9amQSQVQOJvZhw

-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: synapse
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO synapse;

--
-- Name: btree_gist; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;


--
-- Name: EXTENSION btree_gist; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION btree_gist IS 'support for indexing common datatypes in GiST';


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_usage_logs; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.ai_usage_logs (
    id uuid DEFAULT uuidv7() NOT NULL,
    provider character varying(50) NOT NULL,
    operation character varying(50) NOT NULL,
    model character varying(50) NOT NULL,
    prompt_tokens integer NOT NULL,
    completion_tokens integer NOT NULL,
    total_tokens integer NOT NULL,
    latency_ms integer NOT NULL,
    cost_microcents bigint NOT NULL,
    cached_response boolean NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    clinic_id uuid NOT NULL,
    message_id uuid,
    session_id uuid,
    CONSTRAINT ai_usage_logs_completion_tokens_check CHECK ((completion_tokens >= 0)),
    CONSTRAINT ai_usage_logs_latency_ms_check CHECK ((latency_ms >= 0)),
    CONSTRAINT ai_usage_logs_prompt_tokens_check CHECK ((prompt_tokens >= 0)),
    CONSTRAINT ai_usage_logs_total_tokens_check CHECK ((total_tokens >= 0))
);


ALTER TABLE public.ai_usage_logs OWNER TO synapse;

--
-- Name: appointments; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.appointments (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    confirmation_code character varying(10) NOT NULL,
    notes text NOT NULL,
    source character varying(20) NOT NULL,
    clinic_id uuid NOT NULL,
    doctor_id uuid NOT NULL,
    insurance_plan_id uuid,
    patient_id uuid NOT NULL,
    service_id uuid,
    CONSTRAINT chk_appointment_end_after_start CHECK ((end_time > start_time))
);


ALTER TABLE public.appointments OWNER TO synapse;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO synapse;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO synapse;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO synapse;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO synapse;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO synapse;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO synapse;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.chat_messages (
    id uuid DEFAULT uuidv7() NOT NULL,
    role character varying(20) NOT NULL,
    message_type character varying(20) NOT NULL,
    content text NOT NULL,
    metadata jsonb NOT NULL,
    token_count integer,
    sequence_number integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    clinic_id uuid NOT NULL,
    session_id uuid NOT NULL,
    CONSTRAINT chat_messages_sequence_number_check CHECK ((sequence_number >= 0)),
    CONSTRAINT chat_messages_token_count_check CHECK ((token_count >= 0))
);


ALTER TABLE public.chat_messages OWNER TO synapse;

--
-- Name: chat_sessions; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.chat_sessions (
    id uuid DEFAULT uuidv7() NOT NULL,
    session_token character varying(64) NOT NULL,
    ip_hash character varying(64) NOT NULL,
    user_agent character varying(500) NOT NULL,
    locale character varying(10) NOT NULL,
    conversation_context jsonb NOT NULL,
    is_authenticated boolean NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_active_at timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    clinic_id uuid NOT NULL,
    patient_id uuid
);


ALTER TABLE public.chat_sessions OWNER TO synapse;

--
-- Name: clinic_business_hours; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.clinic_business_hours (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    day_of_week smallint NOT NULL,
    open_time time without time zone,
    close_time time without time zone,
    is_closed boolean NOT NULL,
    clinic_id uuid NOT NULL,
    CONSTRAINT chk_clinic_hours_day_of_week CHECK (((day_of_week >= 0) AND (day_of_week <= 6))),
    CONSTRAINT clinic_business_hours_day_of_week_check CHECK ((day_of_week >= 0))
);


ALTER TABLE public.clinic_business_hours OWNER TO synapse;

--
-- Name: clinics; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.clinics (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    address jsonb NOT NULL,
    timezone character varying(50) NOT NULL,
    status character varying(20) NOT NULL
);


ALTER TABLE public.clinics OWNER TO synapse;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO synapse;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO synapse;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO synapse;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO synapse;

--
-- Name: doctor_insurance; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.doctor_insurance (
    id bigint NOT NULL,
    clinic_id uuid NOT NULL,
    doctor_id uuid NOT NULL,
    insurance_plan_id uuid NOT NULL
);


ALTER TABLE public.doctor_insurance OWNER TO synapse;

--
-- Name: doctor_insurance_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.doctor_insurance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_insurance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor_leaves; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.doctor_leaves (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    reason character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    clinic_id uuid NOT NULL,
    doctor_id uuid NOT NULL,
    CONSTRAINT chk_leave_end_after_start CHECK ((end_at > start_at))
);


ALTER TABLE public.doctor_leaves OWNER TO synapse;

--
-- Name: doctor_schedules; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.doctor_schedules (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    day_of_week smallint NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    slot_duration_min smallint NOT NULL,
    is_active boolean NOT NULL,
    clinic_id uuid NOT NULL,
    doctor_id uuid NOT NULL,
    CONSTRAINT chk_schedule_day_of_week CHECK (((day_of_week >= 0) AND (day_of_week <= 6))),
    CONSTRAINT doctor_schedules_day_of_week_check CHECK ((day_of_week >= 0)),
    CONSTRAINT doctor_schedules_slot_duration_min_check CHECK ((slot_duration_min >= 0))
);


ALTER TABLE public.doctor_schedules OWNER TO synapse;

--
-- Name: doctor_services; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.doctor_services (
    id bigint NOT NULL,
    clinic_id uuid NOT NULL,
    doctor_id uuid NOT NULL,
    service_id uuid NOT NULL
);


ALTER TABLE public.doctor_services OWNER TO synapse;

--
-- Name: doctor_services_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.doctor_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor_specialties; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.doctor_specialties (
    id bigint NOT NULL,
    clinic_id uuid NOT NULL,
    doctor_id uuid NOT NULL,
    specialty_id uuid NOT NULL
);


ALTER TABLE public.doctor_specialties OWNER TO synapse;

--
-- Name: doctor_specialties_id_seq; Type: SEQUENCE; Schema: public; Owner: synapse
--

ALTER TABLE public.doctor_specialties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_specialties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctors; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.doctors (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    full_name character varying(255) NOT NULL,
    title character varying(50) NOT NULL,
    bio text NOT NULL,
    photo_url character varying(500) NOT NULL,
    languages character varying(10)[] NOT NULL,
    is_active boolean NOT NULL,
    is_accepting_patients boolean NOT NULL,
    metadata jsonb NOT NULL,
    clinic_id uuid NOT NULL
);


ALTER TABLE public.doctors OWNER TO synapse;

--
-- Name: documents; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.documents (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    title character varying(255) NOT NULL,
    file_name character varying(255) NOT NULL,
    file_type character varying(50) NOT NULL,
    storage_path character varying(500) NOT NULL,
    file_size_bytes integer,
    status character varying(20) NOT NULL,
    chunk_count integer NOT NULL,
    uploaded_by uuid,
    metadata jsonb NOT NULL,
    error_message text NOT NULL,
    clinic_id uuid NOT NULL,
    CONSTRAINT documents_chunk_count_check CHECK ((chunk_count >= 0)),
    CONSTRAINT documents_file_size_bytes_check CHECK ((file_size_bytes >= 0))
);


ALTER TABLE public.documents OWNER TO synapse;

--
-- Name: insurance_plans; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.insurance_plans (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    provider_name character varying(255) NOT NULL,
    plan_name character varying(255) NOT NULL,
    plan_type character varying(50) NOT NULL,
    is_accepted boolean NOT NULL,
    notes text NOT NULL,
    metadata jsonb NOT NULL,
    clinic_id uuid NOT NULL
);


ALTER TABLE public.insurance_plans OWNER TO synapse;

--
-- Name: knowledge_chunks; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.knowledge_chunks (
    id uuid DEFAULT uuidv7() NOT NULL,
    chunk_number integer NOT NULL,
    page_number integer,
    content text NOT NULL,
    token_count integer,
    embedding public.vector(1536),
    embedding_model character varying(50) NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    clinic_id uuid NOT NULL,
    document_id uuid NOT NULL,
    CONSTRAINT knowledge_chunks_chunk_number_check CHECK ((chunk_number >= 0)),
    CONSTRAINT knowledge_chunks_page_number_check CHECK ((page_number >= 0)),
    CONSTRAINT knowledge_chunks_token_count_check CHECK ((token_count >= 0))
);


ALTER TABLE public.knowledge_chunks OWNER TO synapse;

--
-- Name: otp_verifications; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.otp_verifications (
    id uuid DEFAULT uuidv7() NOT NULL,
    phone character varying(20) NOT NULL,
    code_hash character varying(128) NOT NULL,
    attempts smallint NOT NULL,
    max_attempts smallint NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    clinic_id uuid NOT NULL,
    patient_id uuid,
    session_id uuid NOT NULL,
    CONSTRAINT otp_verifications_attempts_check CHECK ((attempts >= 0)),
    CONSTRAINT otp_verifications_max_attempts_check CHECK ((max_attempts >= 0))
);


ALTER TABLE public.otp_verifications OWNER TO synapse;

--
-- Name: patients; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.patients (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    date_of_birth date,
    preferred_language character varying(10) NOT NULL,
    is_verified boolean NOT NULL,
    metadata jsonb NOT NULL,
    clinic_id uuid NOT NULL
);


ALTER TABLE public.patients OWNER TO synapse;

--
-- Name: services; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.services (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    duration_min smallint NOT NULL,
    price_cents integer,
    is_active boolean NOT NULL,
    clinic_id uuid NOT NULL,
    CONSTRAINT services_duration_min_check CHECK ((duration_min >= 0)),
    CONSTRAINT services_price_cents_check CHECK ((price_cents >= 0))
);


ALTER TABLE public.services OWNER TO synapse;

--
-- Name: specialties; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.specialties (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    clinic_id uuid NOT NULL
);


ALTER TABLE public.specialties OWNER TO synapse;

--
-- Name: widget_settings; Type: TABLE; Schema: public; Owner: synapse
--

CREATE TABLE public.widget_settings (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    configuration jsonb NOT NULL,
    clinic_id uuid NOT NULL
);


ALTER TABLE public.widget_settings OWNER TO synapse;

--
-- Name: ai_usage_logs ai_usage_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.ai_usage_logs
    ADD CONSTRAINT ai_usage_logs_pkey PRIMARY KEY (id);


--
-- Name: appointments appointments_confirmation_code_key; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_confirmation_code_key UNIQUE (confirmation_code);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: chat_sessions chat_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (id);


--
-- Name: chat_sessions chat_sessions_session_token_key; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_session_token_key UNIQUE (session_token);


--
-- Name: clinic_business_hours clinic_business_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.clinic_business_hours
    ADD CONSTRAINT clinic_business_hours_pkey PRIMARY KEY (id);


--
-- Name: clinics clinics_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.clinics
    ADD CONSTRAINT clinics_pkey PRIMARY KEY (id);


--
-- Name: clinics clinics_slug_key; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.clinics
    ADD CONSTRAINT clinics_slug_key UNIQUE (slug);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: doctor_insurance doctor_insurance_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_insurance
    ADD CONSTRAINT doctor_insurance_pkey PRIMARY KEY (id);


--
-- Name: doctor_leaves doctor_leaves_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_leaves
    ADD CONSTRAINT doctor_leaves_pkey PRIMARY KEY (id);


--
-- Name: doctor_schedules doctor_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT doctor_schedules_pkey PRIMARY KEY (id);


--
-- Name: doctor_services doctor_services_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_services
    ADD CONSTRAINT doctor_services_pkey PRIMARY KEY (id);


--
-- Name: doctor_specialties doctor_specialties_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_specialties
    ADD CONSTRAINT doctor_specialties_pkey PRIMARY KEY (id);


--
-- Name: doctors doctors_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: appointments excl_appointments_no_overlap; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT excl_appointments_no_overlap EXCLUDE USING gist (doctor_id WITH =, tstzrange(start_time, end_time) WITH &&) WHERE (((status)::text <> ALL ((ARRAY['cancelled'::character varying, 'rescheduled'::character varying])::text[])));


--
-- Name: insurance_plans insurance_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.insurance_plans
    ADD CONSTRAINT insurance_plans_pkey PRIMARY KEY (id);


--
-- Name: knowledge_chunks knowledge_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_pkey PRIMARY KEY (id);


--
-- Name: otp_verifications otp_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.otp_verifications
    ADD CONSTRAINT otp_verifications_pkey PRIMARY KEY (id);


--
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: specialties specialties_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.specialties
    ADD CONSTRAINT specialties_pkey PRIMARY KEY (id);


--
-- Name: knowledge_chunks uq_chunk_document_number; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT uq_chunk_document_number UNIQUE (document_id, chunk_number);


--
-- Name: clinic_business_hours uq_clinic_business_hours_day; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.clinic_business_hours
    ADD CONSTRAINT uq_clinic_business_hours_day UNIQUE (clinic_id, day_of_week);


--
-- Name: doctor_insurance uq_doctor_insurance; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_insurance
    ADD CONSTRAINT uq_doctor_insurance UNIQUE (doctor_id, insurance_plan_id);


--
-- Name: doctor_services uq_doctor_service; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_services
    ADD CONSTRAINT uq_doctor_service UNIQUE (doctor_id, service_id);


--
-- Name: doctor_specialties uq_doctor_specialty; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_specialties
    ADD CONSTRAINT uq_doctor_specialty UNIQUE (doctor_id, specialty_id);


--
-- Name: chat_messages uq_message_session_sequence; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT uq_message_session_sequence UNIQUE (session_id, sequence_number);


--
-- Name: patients uq_patient_clinic_phone; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT uq_patient_clinic_phone UNIQUE (clinic_id, phone);


--
-- Name: specialties uq_specialty_clinic_slug; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.specialties
    ADD CONSTRAINT uq_specialty_clinic_slug UNIQUE (clinic_id, slug);


--
-- Name: widget_settings widget_settings_clinic_id_key; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.widget_settings
    ADD CONSTRAINT widget_settings_clinic_id_key UNIQUE (clinic_id);


--
-- Name: widget_settings widget_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.widget_settings
    ADD CONSTRAINT widget_settings_pkey PRIMARY KEY (id);


--
-- Name: ai_usage_lo_clinic__35bfb4_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX ai_usage_lo_clinic__35bfb4_idx ON public.ai_usage_logs USING btree (clinic_id, operation, created_at);


--
-- Name: ai_usage_lo_clinic__734e7c_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX ai_usage_lo_clinic__734e7c_idx ON public.ai_usage_logs USING btree (clinic_id, cached_response, created_at);


--
-- Name: ai_usage_lo_clinic__897919_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX ai_usage_lo_clinic__897919_idx ON public.ai_usage_logs USING btree (clinic_id, created_at);


--
-- Name: ai_usage_lo_session_5cc41e_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX ai_usage_lo_session_5cc41e_idx ON public.ai_usage_logs USING btree (session_id, created_at);


--
-- Name: ai_usage_logs_clinic_id_817913fe; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX ai_usage_logs_clinic_id_817913fe ON public.ai_usage_logs USING btree (clinic_id);


--
-- Name: ai_usage_logs_message_id_799a5cd9; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX ai_usage_logs_message_id_799a5cd9 ON public.ai_usage_logs USING btree (message_id);


--
-- Name: ai_usage_logs_session_id_08acc437; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX ai_usage_logs_session_id_08acc437 ON public.ai_usage_logs USING btree (session_id);


--
-- Name: appointment_clinic__564357_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointment_clinic__564357_idx ON public.appointments USING btree (clinic_id, patient_id);


--
-- Name: appointment_clinic__67cbfc_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointment_clinic__67cbfc_idx ON public.appointments USING btree (clinic_id, status, start_time);


--
-- Name: appointment_clinic__accbd6_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointment_clinic__accbd6_idx ON public.appointments USING btree (clinic_id, doctor_id, start_time);


--
-- Name: appointments_clinic_id_a77c0a21; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointments_clinic_id_a77c0a21 ON public.appointments USING btree (clinic_id);


--
-- Name: appointments_confirmation_code_4d4f9b73_like; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointments_confirmation_code_4d4f9b73_like ON public.appointments USING btree (confirmation_code varchar_pattern_ops);


--
-- Name: appointments_doctor_id_96635781; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointments_doctor_id_96635781 ON public.appointments USING btree (doctor_id);


--
-- Name: appointments_insurance_plan_id_dc554431; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointments_insurance_plan_id_dc554431 ON public.appointments USING btree (insurance_plan_id);


--
-- Name: appointments_patient_id_b2db55d3; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointments_patient_id_b2db55d3 ON public.appointments USING btree (patient_id);


--
-- Name: appointments_service_id_00b454f1; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX appointments_service_id_00b454f1 ON public.appointments USING btree (service_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: chat_messag_clinic__04353d_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_messag_clinic__04353d_idx ON public.chat_messages USING btree (clinic_id, created_at);


--
-- Name: chat_messag_session_597c4e_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_messag_session_597c4e_idx ON public.chat_messages USING btree (session_id, created_at);


--
-- Name: chat_messag_session_e65470_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_messag_session_e65470_idx ON public.chat_messages USING btree (session_id, message_type);


--
-- Name: chat_messages_clinic_id_a94b4ccb; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_messages_clinic_id_a94b4ccb ON public.chat_messages USING btree (clinic_id);


--
-- Name: chat_messages_session_id_c5afc568; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_messages_session_id_c5afc568 ON public.chat_messages USING btree (session_id);


--
-- Name: chat_sessio_clinic__413423_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_sessio_clinic__413423_idx ON public.chat_sessions USING btree (clinic_id, status);


--
-- Name: chat_sessio_clinic__8c407f_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_sessio_clinic__8c407f_idx ON public.chat_sessions USING btree (clinic_id, patient_id);


--
-- Name: chat_sessio_clinic__afa3f5_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_sessio_clinic__afa3f5_idx ON public.chat_sessions USING btree (clinic_id, last_active_at);


--
-- Name: chat_sessions_clinic_id_69dc1a05; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_sessions_clinic_id_69dc1a05 ON public.chat_sessions USING btree (clinic_id);


--
-- Name: chat_sessions_patient_id_1fac234c; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_sessions_patient_id_1fac234c ON public.chat_sessions USING btree (patient_id);


--
-- Name: chat_sessions_session_token_251a340d_like; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX chat_sessions_session_token_251a340d_like ON public.chat_sessions USING btree (session_token varchar_pattern_ops);


--
-- Name: clinic_busi_clinic__58541f_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX clinic_busi_clinic__58541f_idx ON public.clinic_business_hours USING btree (clinic_id);


--
-- Name: clinic_business_hours_clinic_id_9129c390; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX clinic_business_hours_clinic_id_9129c390 ON public.clinic_business_hours USING btree (clinic_id);


--
-- Name: clinics_slug_6d88938a_like; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX clinics_slug_6d88938a_like ON public.clinics USING btree (slug varchar_pattern_ops);


--
-- Name: clinics_status_953dfa_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX clinics_status_953dfa_idx ON public.clinics USING btree (status);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: doctor_insu_clinic__2d31a0_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_insu_clinic__2d31a0_idx ON public.doctor_insurance USING btree (clinic_id, insurance_plan_id);


--
-- Name: doctor_insu_clinic__91fc6d_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_insu_clinic__91fc6d_idx ON public.doctor_insurance USING btree (clinic_id, doctor_id);


--
-- Name: doctor_insurance_clinic_id_0946ec92; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_insurance_clinic_id_0946ec92 ON public.doctor_insurance USING btree (clinic_id);


--
-- Name: doctor_insurance_doctor_id_9fdd1125; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_insurance_doctor_id_9fdd1125 ON public.doctor_insurance USING btree (doctor_id);


--
-- Name: doctor_insurance_insurance_plan_id_f169015a; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_insurance_insurance_plan_id_f169015a ON public.doctor_insurance USING btree (insurance_plan_id);


--
-- Name: doctor_leav_clinic__1af543_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_leav_clinic__1af543_idx ON public.doctor_leaves USING btree (clinic_id, doctor_id, is_active);


--
-- Name: doctor_leav_clinic__78d270_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_leav_clinic__78d270_idx ON public.doctor_leaves USING btree (clinic_id, doctor_id, start_at, end_at);


--
-- Name: doctor_leaves_clinic_id_000de852; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_leaves_clinic_id_000de852 ON public.doctor_leaves USING btree (clinic_id);


--
-- Name: doctor_leaves_doctor_id_803dc326; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_leaves_doctor_id_803dc326 ON public.doctor_leaves USING btree (doctor_id);


--
-- Name: doctor_sche_clinic__376204_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_sche_clinic__376204_idx ON public.doctor_schedules USING btree (clinic_id, doctor_id, is_active);


--
-- Name: doctor_sche_clinic__3b5877_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_sche_clinic__3b5877_idx ON public.doctor_schedules USING btree (clinic_id, doctor_id, day_of_week);


--
-- Name: doctor_schedules_clinic_id_43453aa9; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_schedules_clinic_id_43453aa9 ON public.doctor_schedules USING btree (clinic_id);


--
-- Name: doctor_schedules_doctor_id_44f71506; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_schedules_doctor_id_44f71506 ON public.doctor_schedules USING btree (doctor_id);


--
-- Name: doctor_serv_clinic__259969_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_serv_clinic__259969_idx ON public.doctor_services USING btree (clinic_id, doctor_id);


--
-- Name: doctor_serv_clinic__2d3f95_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_serv_clinic__2d3f95_idx ON public.doctor_services USING btree (clinic_id, service_id);


--
-- Name: doctor_services_clinic_id_f8a67b6a; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_services_clinic_id_f8a67b6a ON public.doctor_services USING btree (clinic_id);


--
-- Name: doctor_services_doctor_id_4b7b4abf; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_services_doctor_id_4b7b4abf ON public.doctor_services USING btree (doctor_id);


--
-- Name: doctor_services_service_id_ba5c16d2; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_services_service_id_ba5c16d2 ON public.doctor_services USING btree (service_id);


--
-- Name: doctor_spec_clinic__63bbbe_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_spec_clinic__63bbbe_idx ON public.doctor_specialties USING btree (clinic_id, specialty_id);


--
-- Name: doctor_spec_clinic__cad5af_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_spec_clinic__cad5af_idx ON public.doctor_specialties USING btree (clinic_id, doctor_id);


--
-- Name: doctor_specialties_clinic_id_71db5383; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_specialties_clinic_id_71db5383 ON public.doctor_specialties USING btree (clinic_id);


--
-- Name: doctor_specialties_doctor_id_ce6ab67c; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_specialties_doctor_id_ce6ab67c ON public.doctor_specialties USING btree (doctor_id);


--
-- Name: doctor_specialties_specialty_id_58c837fe; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctor_specialties_specialty_id_58c837fe ON public.doctor_specialties USING btree (specialty_id);


--
-- Name: doctors_clinic__06d425_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctors_clinic__06d425_idx ON public.doctors USING btree (clinic_id, is_active);


--
-- Name: doctors_clinic_id_37c3b1d3; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctors_clinic_id_37c3b1d3 ON public.doctors USING btree (clinic_id);


--
-- Name: doctors_is_deleted_7808ff87; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX doctors_is_deleted_7808ff87 ON public.doctors USING btree (is_deleted);


--
-- Name: documents_clinic__052998_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX documents_clinic__052998_idx ON public.documents USING btree (clinic_id, created_at);


--
-- Name: documents_clinic__ebdf1e_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX documents_clinic__ebdf1e_idx ON public.documents USING btree (clinic_id, status);


--
-- Name: documents_clinic_id_a4698c90; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX documents_clinic_id_a4698c90 ON public.documents USING btree (clinic_id);


--
-- Name: documents_is_deleted_1901192a; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX documents_is_deleted_1901192a ON public.documents USING btree (is_deleted);


--
-- Name: idx_kc_content_fts; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX idx_kc_content_fts ON public.knowledge_chunks USING gin (to_tsvector('english'::regconfig, content));


--
-- Name: idx_kc_embedding_hnsw; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX idx_kc_embedding_hnsw ON public.knowledge_chunks USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');


--
-- Name: insurance_p_clinic__c42ce1_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX insurance_p_clinic__c42ce1_idx ON public.insurance_plans USING btree (clinic_id, is_accepted);


--
-- Name: insurance_plans_clinic_id_f0257d9e; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX insurance_plans_clinic_id_f0257d9e ON public.insurance_plans USING btree (clinic_id);


--
-- Name: insurance_plans_is_deleted_5e2f7c89; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX insurance_plans_is_deleted_5e2f7c89 ON public.insurance_plans USING btree (is_deleted);


--
-- Name: knowledge_c_clinic__fe24e1_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX knowledge_c_clinic__fe24e1_idx ON public.knowledge_chunks USING btree (clinic_id, document_id);


--
-- Name: knowledge_c_documen_775e8a_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX knowledge_c_documen_775e8a_idx ON public.knowledge_chunks USING btree (document_id, page_number);


--
-- Name: knowledge_chunks_clinic_id_3277e80a; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX knowledge_chunks_clinic_id_3277e80a ON public.knowledge_chunks USING btree (clinic_id);


--
-- Name: knowledge_chunks_document_id_33cf844c; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX knowledge_chunks_document_id_33cf844c ON public.knowledge_chunks USING btree (document_id);


--
-- Name: otp_verific_clinic__9a7639_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX otp_verific_clinic__9a7639_idx ON public.otp_verifications USING btree (clinic_id, phone, expires_at);


--
-- Name: otp_verific_session_a31074_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX otp_verific_session_a31074_idx ON public.otp_verifications USING btree (session_id, created_at);


--
-- Name: otp_verifications_clinic_id_b2b3a931; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX otp_verifications_clinic_id_b2b3a931 ON public.otp_verifications USING btree (clinic_id);


--
-- Name: otp_verifications_patient_id_e31c047b; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX otp_verifications_patient_id_e31c047b ON public.otp_verifications USING btree (patient_id);


--
-- Name: otp_verifications_session_id_e6529f32; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX otp_verifications_session_id_e6529f32 ON public.otp_verifications USING btree (session_id);


--
-- Name: patients_clinic__b002b7_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX patients_clinic__b002b7_idx ON public.patients USING btree (clinic_id, last_name);


--
-- Name: patients_clinic__f94219_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX patients_clinic__f94219_idx ON public.patients USING btree (clinic_id, first_name);


--
-- Name: patients_clinic_id_828ae627; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX patients_clinic_id_828ae627 ON public.patients USING btree (clinic_id);


--
-- Name: services_clinic__0d919a_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX services_clinic__0d919a_idx ON public.services USING btree (clinic_id, is_active);


--
-- Name: services_clinic_id_897eb372; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX services_clinic_id_897eb372 ON public.services USING btree (clinic_id);


--
-- Name: services_is_deleted_7835b28a; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX services_is_deleted_7835b28a ON public.services USING btree (is_deleted);


--
-- Name: specialties_clinic__17c602_idx; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX specialties_clinic__17c602_idx ON public.specialties USING btree (clinic_id, is_active);


--
-- Name: specialties_clinic_id_b3f42a9c; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX specialties_clinic_id_b3f42a9c ON public.specialties USING btree (clinic_id);


--
-- Name: specialties_is_deleted_f24fc65f; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX specialties_is_deleted_f24fc65f ON public.specialties USING btree (is_deleted);


--
-- Name: specialties_slug_58c75cfd; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX specialties_slug_58c75cfd ON public.specialties USING btree (slug);


--
-- Name: specialties_slug_58c75cfd_like; Type: INDEX; Schema: public; Owner: synapse
--

CREATE INDEX specialties_slug_58c75cfd_like ON public.specialties USING btree (slug varchar_pattern_ops);


--
-- Name: uq_patient_clinic_email; Type: INDEX; Schema: public; Owner: synapse
--

CREATE UNIQUE INDEX uq_patient_clinic_email ON public.patients USING btree (clinic_id, email) WHERE (NOT ((email)::text = ''::text));


--
-- Name: ai_usage_logs ai_usage_logs_clinic_id_817913fe_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.ai_usage_logs
    ADD CONSTRAINT ai_usage_logs_clinic_id_817913fe_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ai_usage_logs ai_usage_logs_message_id_799a5cd9_fk_chat_messages_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.ai_usage_logs
    ADD CONSTRAINT ai_usage_logs_message_id_799a5cd9_fk_chat_messages_id FOREIGN KEY (message_id) REFERENCES public.chat_messages(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ai_usage_logs ai_usage_logs_session_id_08acc437_fk_chat_sessions_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.ai_usage_logs
    ADD CONSTRAINT ai_usage_logs_session_id_08acc437_fk_chat_sessions_id FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments appointments_clinic_id_a77c0a21_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_clinic_id_a77c0a21_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments appointments_doctor_id_96635781_fk_doctors_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_doctor_id_96635781_fk_doctors_id FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments appointments_insurance_plan_id_dc554431_fk_insurance_plans_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_insurance_plan_id_dc554431_fk_insurance_plans_id FOREIGN KEY (insurance_plan_id) REFERENCES public.insurance_plans(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments appointments_patient_id_b2db55d3_fk_patients_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_patient_id_b2db55d3_fk_patients_id FOREIGN KEY (patient_id) REFERENCES public.patients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: appointments appointments_service_id_00b454f1_fk_services_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_service_id_00b454f1_fk_services_id FOREIGN KEY (service_id) REFERENCES public.services(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_messages chat_messages_clinic_id_a94b4ccb_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_clinic_id_a94b4ccb_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_messages chat_messages_session_id_c5afc568_fk_chat_sessions_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_session_id_c5afc568_fk_chat_sessions_id FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_sessions chat_sessions_clinic_id_69dc1a05_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_clinic_id_69dc1a05_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_sessions chat_sessions_patient_id_1fac234c_fk_patients_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_patient_id_1fac234c_fk_patients_id FOREIGN KEY (patient_id) REFERENCES public.patients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinic_business_hours clinic_business_hours_clinic_id_9129c390_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.clinic_business_hours
    ADD CONSTRAINT clinic_business_hours_clinic_id_9129c390_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_insurance doctor_insurance_clinic_id_0946ec92_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_insurance
    ADD CONSTRAINT doctor_insurance_clinic_id_0946ec92_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_insurance doctor_insurance_doctor_id_9fdd1125_fk_doctors_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_insurance
    ADD CONSTRAINT doctor_insurance_doctor_id_9fdd1125_fk_doctors_id FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_insurance doctor_insurance_insurance_plan_id_f169015a_fk_insurance; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_insurance
    ADD CONSTRAINT doctor_insurance_insurance_plan_id_f169015a_fk_insurance FOREIGN KEY (insurance_plan_id) REFERENCES public.insurance_plans(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_leaves doctor_leaves_clinic_id_000de852_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_leaves
    ADD CONSTRAINT doctor_leaves_clinic_id_000de852_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_leaves doctor_leaves_doctor_id_803dc326_fk_doctors_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_leaves
    ADD CONSTRAINT doctor_leaves_doctor_id_803dc326_fk_doctors_id FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_schedules doctor_schedules_clinic_id_43453aa9_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT doctor_schedules_clinic_id_43453aa9_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_schedules doctor_schedules_doctor_id_44f71506_fk_doctors_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT doctor_schedules_doctor_id_44f71506_fk_doctors_id FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_services doctor_services_clinic_id_f8a67b6a_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_services
    ADD CONSTRAINT doctor_services_clinic_id_f8a67b6a_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_services doctor_services_doctor_id_4b7b4abf_fk_doctors_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_services
    ADD CONSTRAINT doctor_services_doctor_id_4b7b4abf_fk_doctors_id FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_services doctor_services_service_id_ba5c16d2_fk_services_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_services
    ADD CONSTRAINT doctor_services_service_id_ba5c16d2_fk_services_id FOREIGN KEY (service_id) REFERENCES public.services(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_specialties doctor_specialties_clinic_id_71db5383_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_specialties
    ADD CONSTRAINT doctor_specialties_clinic_id_71db5383_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_specialties doctor_specialties_doctor_id_ce6ab67c_fk_doctors_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_specialties
    ADD CONSTRAINT doctor_specialties_doctor_id_ce6ab67c_fk_doctors_id FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctor_specialties doctor_specialties_specialty_id_58c837fe_fk_specialties_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctor_specialties
    ADD CONSTRAINT doctor_specialties_specialty_id_58c837fe_fk_specialties_id FOREIGN KEY (specialty_id) REFERENCES public.specialties(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctors doctors_clinic_id_37c3b1d3_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_clinic_id_37c3b1d3_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents documents_clinic_id_a4698c90_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_clinic_id_a4698c90_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: insurance_plans insurance_plans_clinic_id_f0257d9e_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.insurance_plans
    ADD CONSTRAINT insurance_plans_clinic_id_f0257d9e_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: knowledge_chunks knowledge_chunks_clinic_id_3277e80a_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_clinic_id_3277e80a_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: knowledge_chunks knowledge_chunks_document_id_33cf844c_fk_documents_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_document_id_33cf844c_fk_documents_id FOREIGN KEY (document_id) REFERENCES public.documents(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_verifications otp_verifications_clinic_id_b2b3a931_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.otp_verifications
    ADD CONSTRAINT otp_verifications_clinic_id_b2b3a931_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_verifications otp_verifications_patient_id_e31c047b_fk_patients_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.otp_verifications
    ADD CONSTRAINT otp_verifications_patient_id_e31c047b_fk_patients_id FOREIGN KEY (patient_id) REFERENCES public.patients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_verifications otp_verifications_session_id_e6529f32_fk_chat_sessions_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.otp_verifications
    ADD CONSTRAINT otp_verifications_session_id_e6529f32_fk_chat_sessions_id FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients patients_clinic_id_828ae627_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_clinic_id_828ae627_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: services services_clinic_id_897eb372_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_clinic_id_897eb372_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: specialties specialties_clinic_id_b3f42a9c_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.specialties
    ADD CONSTRAINT specialties_clinic_id_b3f42a9c_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: widget_settings widget_settings_clinic_id_5e8dd1d4_fk_clinics_id; Type: FK CONSTRAINT; Schema: public; Owner: synapse
--

ALTER TABLE ONLY public.widget_settings
    ADD CONSTRAINT widget_settings_clinic_id_5e8dd1d4_fk_clinics_id FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict mkP3GKu6PYIHA70xWhJFrVx9Iu1xFxqvfWI4bMrA0etHEzmuJ9amQSQVQOJvZhw

