# Generated by Django 5.2.16 on 2026-08-11 14:32

import core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_clinic_clinic_type_clinic_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('paddle_price_id_sandbox', models.CharField(blank=True, default='', max_length=64)),
                ('paddle_price_id_live', models.CharField(blank=True, default='', max_length=64)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10)),
                ('display_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('display_currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paddle_event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('notification_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='clinics.clinic')),
            ],
            options={
                'db_table': 'billing_events',
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='billing_eve_clinic__809151_idx'), models.Index(fields=['event_type', 'created_at'], name='billing_eve_event_t_9ff865_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paddle_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('paddle_subscription_id', models.CharField(blank=True, default='', max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='incomplete', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinics.clinic')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_subscriptions',
                'indexes': [models.Index(fields=['paddle_customer_id'], name='billing_sub_paddle__4afadf_idx')],
            },
        ),
    ]
