# Generated by Django 5.2.16 on 2026-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscription_paddle_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_period_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
