# Generated by Django 5.2.16 on 2026-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_id_alter_clinicbusinesshours_id'),
        ('insurance', '0002_alter_insuranceplan_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='insuranceplan',
            name='insurance_p_clinic__c42ce1_idx',
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='insuranceplan',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['clinic', 'is_accepted'], name='idx_ins_accepted_live'),
        ),
    ]
