# Generated by Django 5.2.16 on 2026-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinic_status'),
        ('services', '0003_remove_service_services_clinic__0d919a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='service',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['clinic', 'code'], name='idx_services_code_live'),
        ),
    ]
