# Generated by Django 5.2.16 on 2026-08-12 12:39

import core.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0006_business_hours_multi_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(choices=[('providers', 'Providers'), ('services', 'Services'), ('specialties', 'Specialties')], max_length=16)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('mapped', 'Mapped'), ('validated', 'Validated'), ('reviewed', 'Reviewed'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('storage_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('sample_rows', models.JSONField(blank=True, default=list)),
                ('total_row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_jobs',
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('canonical_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('needs_review', 'Needs Review'), ('ready', 'Ready'), ('duplicate', 'Possible Duplicate'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('committed', 'Committed')], default='needs_review', max_length=16)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('duplicate_match', models.JSONField(blank=True, null=True)),
                ('created_entity_type', models.CharField(blank=True, default='', max_length=16)),
                ('created_entity_id', models.UUIDField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='importer.importjob')),
            ],
            options={
                'db_table': 'import_records',
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['clinic', 'status'], name='import_jobs_clinic__e0a5da_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['clinic', 'record_type', 'created_at'], name='import_jobs_clinic__3759e3_idx'),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['job', 'status'], name='import_reco_job_id_a9b1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['clinic', 'job'], name='import_reco_clinic__205c6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrecord',
            constraint=models.UniqueConstraint(fields=('job', 'row_number'), name='uq_import_record_job_row'),
        ),
    ]
