# Generated by Django 5.2.16 on 2026-08-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='record_type',
            field=models.CharField(choices=[('providers', 'Providers'), ('services', 'Services'), ('specialties', 'Specialties'), ('insurance', 'Insurance')], max_length=16),
        ),
    ]
