# Generated by Django 5.2.16 on 2026-08-19 08:25

import core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockVerificationRecord',
            fields=[
                ('id', models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to', models.CharField(db_index=True, max_length=255)),
                ('channel', models.CharField(max_length=16)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mock_verification_records',
                'indexes': [models.Index(fields=['to', 'channel', 'created_at'], name='mock_verifi_to_4a3787_idx')],
            },
        ),
    ]
