# Generated by Django 5.2.16 on 2026-07-15 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('onboarding', 'Onboarding')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'clinics',
                'indexes': [models.Index(fields=['status'], name='clinics_status_953dfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicBusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'clinic business hours',
                'db_table': 'clinic_business_hours',
                'indexes': [models.Index(fields=['clinic'], name='clinic_busi_clinic__58541f_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'day_of_week'), name='uq_clinic_business_hours_day'), models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='chk_clinic_hours_day_of_week')],
            },
        ),
    ]
