# Generated by Django 5.2.16 on 2026-08-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_id_alter_clinicbusinesshours_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='onboarding', max_length=20),
        ),
    ]
