# Generated by Django 5.2.16 on 2026-08-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(blank=True, choices=[('dermatology', 'Dermatology'), ('dental', 'Dental'), ('aesthetics', 'Aesthetics / Med Spa'), ('general_medicine', 'General Medicine'), ('urgent_care', 'Urgent Care'), ('laboratory', 'Laboratory'), ('cosmetic_surgery', 'Cosmetic / Plastic Surgery'), ('multi_specialty', 'Multi-Specialty'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='clinic',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='onboarding_step',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
