# Generated by Django 5.2.16 on 2026-08-11 15:38

import core.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_clinic_type_clinic_onboarding_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicApplication',
            fields=[
                ('id', models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('num_doctors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_scheduling_system', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('plan_slug', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('converted_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='clinics.clinic')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_clinic_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_applications',
                'indexes': [models.Index(fields=['status', 'created_at'], name='clinic_appl_status_2a7ffa_idx'), models.Index(fields=['work_email'], name='clinic_appl_work_em_824928_idx')],
            },
        ),
    ]
