# Generated by Django 5.2.16 on 2026-08-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinicapplication'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicbusinesshours',
            name='uq_clinic_business_hours_day',
        ),
        migrations.AddIndex(
            model_name='clinicbusinesshours',
            index=models.Index(fields=['clinic', 'day_of_week'], name='idx_clinic_hours_day'),
        ),
    ]
