# Generated by Django 5.2.16 on 2026-08-12 14:01

from django.db import migrations, models


def rename_general_medicine_to_primary_care(apps, schema_editor):
    Clinic = apps.get_model("clinics", "Clinic")
    Clinic.objects.filter(clinic_type="general_medicine").update(clinic_type="primary_care")


def rename_primary_care_to_general_medicine(apps, schema_editor):
    Clinic = apps.get_model("clinics", "Clinic")
    Clinic.objects.filter(clinic_type="primary_care").update(clinic_type="general_medicine")


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_business_hours_multi_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(blank=True, choices=[('primary_care', 'Primary Care'), ('medical_specialty', 'Medical Specialty'), ('neurology', 'Neurology'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('aesthetics', 'Aesthetics / Med Spa'), ('dental', 'Dental'), ('physical_therapy', 'Physical Therapy'), ('behavioral_health', 'Mental / Behavioral Health'), ('laboratory', 'Laboratory / Diagnostics'), ('urgent_care', 'Urgent Care'), ('cosmetic_surgery', 'Cosmetic / Plastic Surgery'), ('multi_specialty', 'Multi-Specialty'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.RunPython(
            rename_general_medicine_to_primary_care,
            rename_primary_care_to_general_medicine,
        ),
    ]
