# Generated by Django 5.2.16 on 2026-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinictype_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicapplication',
            name='source',
            field=models.CharField(choices=[('get_started', 'Get Started'), ('demo_request', 'Demo Request')], default='get_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicapplication',
            name='plan_slug',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
