# Generated by Django 5.2.16 on 2026-09-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinicapplication_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='allowed_origins',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
