# Generated by Django 5.2.16 on 2026-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_id_alter_clinicbusinesshours_id'),
        ('knowledge', '0003_alter_document_id_alter_knowledgechunk_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_clinic__ebdf1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_clinic__052998_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['clinic', 'status'], name='idx_docs_status_live'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['clinic', 'created_at'], name='idx_docs_created_live'),
        ),
    ]
