# Generated by Django 5.2.16 on 2026-07-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_id_alter_clinicbusinesshours_id'),
        ('knowledge', '0005_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='chunk_type',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('list', 'List'), ('heading', 'Heading'), ('mixed', 'Mixed')], default='paragraph', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('chunked', 'Chunked'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'page_start'], name='knowledge_c_documen_2a1f6f_idx'),
        ),
    ]
