# Generated by Django 5.2.16 on 2026-07-16 11:38

import core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='id',
            field=models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
