# Generated by Django 5.2.16 on 2026-08-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_id_alter_chatsession_id_and_more'),
        ('clinics', '0003_alter_clinic_status'),
        ('patients', '0003_patient_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=16),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['clinic', 'email', 'expires_at'], name='otp_verific_clinic__93f7a4_idx'),
        ),
    ]
