# Generated by Django 5.2.16 on 2026-08-21 13:15

import core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_otpverification_channel_otpverification_email_and_more'),
        ('clinics', '0008_clinicapplication_source_and_more'),
        ('patients', '0003_patient_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatVisitor',
            fields=[
                ('id', models.UUIDField(db_default=core.uuid.UuidV7(), default=core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('visitor_key', models.CharField(max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_visitors', to='patients.patient')),
            ],
            options={
                'db_table': 'chat_visitors',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='chatbot.chatvisitor'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['visitor', 'last_active_at'], name='chat_sessio_visitor_66c543_idx'),
        ),
        migrations.AddIndex(
            model_name='chatvisitor',
            index=models.Index(fields=['clinic', 'patient'], name='chat_visito_clinic__8082c3_idx'),
        ),
    ]
