# Generated by Django 5.2.16 on 2026-08-27 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_add_chat_visitor'),
        ('clinics', '0008_clinicapplication_source_and_more'),
        ('patients', '0003_patient_verified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['clinic', 'created_by_user', 'last_active_at'], name='chat_sessio_clinic__dd4517_idx'),
        ),
    ]
