# Generated by Django 5.2.16 on 2026-07-15 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
            ],
            options={
                'db_table': 'patients',
                'indexes': [models.Index(fields=['clinic', 'first_name'], name='patients_clinic__f94219_idx'), models.Index(fields=['clinic', 'last_name'], name='patients_clinic__b002b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'phone'), name='uq_patient_clinic_phone'), models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('clinic', 'email'), name='uq_patient_clinic_email')],
            },
        ),
    ]
