# Generated by Django 5.2.16 on 2026-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration): #why Migration(migrations.Migration) what's the difference between this and the other migrations? this is the migration file for the patient model. why we are adding the verified_at field? because we want to store the date and time when the patient is verified. a

    dependencies = [
        ('patients', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Set when phone OTP verification succeeds.', null=True),
        ),
    ]
