# Generated by Django 5.2.16 on 2026-08-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob_check_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob_check_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
