# Generated by Django 5.2.16 on 2026-09-07 08:15

import django.db.models.functions.datetime
from django.db import migrations, models


def _clear_future_dobs(apps, schema_editor):
    from django.utils import timezone

    Patient = apps.get_model("patients", "Patient")
    Patient.objects.filter(date_of_birth__gt=timezone.localdate()).update(
        date_of_birth=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0009_clinic_allowed_origins"),
        ("patients", "0004_patient_dob_check_attempts_and_more"),
    ]

    operations = [
        migrations.RunPython(_clear_future_dobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_of_birth__isnull", True),
                    (
                        "date_of_birth__lte",
                        django.db.models.functions.datetime.TruncDate(
                            django.db.models.functions.datetime.Now()
                        ),
                    ),
                    _connector="OR",
                ),
                name="chk_patient_dob_not_future",
            ),
        ),
    ]
