# Generated by Django 5.2.16 on 2026-07-15 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('cache', 'Cache')], default='openai', max_length=50)),
                ('operation', models.CharField(choices=[('chat_completion', 'Chat Completion'), ('embedding', 'Embedding'), ('intent_classification', 'Intent Classification')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_microcents', models.BigIntegerField(default=0)),
                ('cached_response', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='chatbot.chatmessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='ai_usage_lo_clinic__897919_idx'), models.Index(fields=['clinic', 'operation', 'created_at'], name='ai_usage_lo_clinic__35bfb4_idx'), models.Index(fields=['clinic', 'cached_response', 'created_at'], name='ai_usage_lo_clinic__734e7c_idx'), models.Index(fields=['session', 'created_at'], name='ai_usage_lo_session_5cc41e_idx')],
            },
        ),
    ]
