# Generated by Django 5.2.16 on 2026-07-15 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.JSONField(default=dict)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_settings', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'widget settings',
                'db_table': 'widget_settings',
            },
        ),
    ]
