# Generated by Django 5.2.16 on 2026-07-15 11:23

import apps.doctors.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('insurance', '0001_initial'),
        ('services', '0001_initial'),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=apps.doctors.models.default_languages, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepting_patients', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_insurances', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_insurances', to='doctors.doctor')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_insurances', to='insurance.insuranceplan')),
            ],
            options={
                'db_table': 'doctor_insurance',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance_plans',
            field=models.ManyToManyField(related_name='doctors', through='doctors.DoctorInsurance', to='insurance.insuranceplan'),
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctor')),
            ],
            options={
                'db_table': 'doctor_leaves',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_min', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'db_table': 'doctor_schedules',
            },
        ),
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_services', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_services', to='doctors.doctor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_services', to='services.service')),
            ],
            options={
                'db_table': 'doctor_services',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(related_name='doctors', through='doctors.DoctorService', to='services.service'),
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='doctors.doctor')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='specialties.specialty')),
            ],
            options={
                'db_table': 'doctor_specialties',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='doctors', through='doctors.DoctorSpecialty', to='specialties.specialty'),
        ),
        migrations.AddIndex(
            model_name='doctorinsurance',
            index=models.Index(fields=['clinic', 'insurance_plan'], name='doctor_insu_clinic__2d31a0_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorinsurance',
            index=models.Index(fields=['clinic', 'doctor'], name='doctor_insu_clinic__91fc6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorinsurance',
            constraint=models.UniqueConstraint(fields=('doctor', 'insurance_plan'), name='uq_doctor_insurance'),
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['clinic', 'doctor', 'start_at', 'end_at'], name='doctor_leav_clinic__78d270_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['clinic', 'doctor', 'is_active'], name='doctor_leav_clinic__1af543_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorleave',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='chk_leave_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['clinic', 'doctor', 'day_of_week'], name='doctor_sche_clinic__3b5877_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['clinic', 'doctor', 'is_active'], name='doctor_sche_clinic__376204_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='chk_schedule_day_of_week'),
        ),
        migrations.AddIndex(
            model_name='doctorservice',
            index=models.Index(fields=['clinic', 'service'], name='doctor_serv_clinic__2d3f95_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorservice',
            index=models.Index(fields=['clinic', 'doctor'], name='doctor_serv_clinic__259969_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorservice',
            constraint=models.UniqueConstraint(fields=('doctor', 'service'), name='uq_doctor_service'),
        ),
        migrations.AddIndex(
            model_name='doctorspecialty',
            index=models.Index(fields=['clinic', 'specialty'], name='doctor_spec_clinic__63bbbe_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecialty',
            index=models.Index(fields=['clinic', 'doctor'], name='doctor_spec_clinic__cad5af_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorspecialty',
            constraint=models.UniqueConstraint(fields=('doctor', 'specialty'), name='uq_doctor_specialty'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['clinic', 'is_active'], name='doctors_clinic__06d425_idx'),
        ),
    ]
