# Generated by Django 5.2.16 on 2026-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_id_alter_clinicbusinesshours_id'),
        ('doctors', '0002_alter_doctor_id_alter_doctorleave_id_and_more'),
        ('insurance', '0002_alter_insuranceplan_id'),
        ('services', '0002_alter_service_id'),
        ('specialties', '0002_alter_specialty_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctor',
            name='doctors_clinic__06d425_idx',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['clinic', 'is_active'], name='idx_doctors_active_live'),
        ),
    ]
